image: "python:3.7"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - venv/

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SRC_DIR: "delirium"

stages:
  - analysis
  - testing

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python -m pip install -r requirements.txt

flake8:
  stage: analysis
  script:
  - python -m pip install flake8
  - flake8 ${SRC_DIR}

pylint:
  stage: analysis
  allow_failure: true
  script:
  - python -m pip install pylint
  - pylint ${SRC_DIR}

bandit:
  stage: analysis
  script:
  - python -m pip install bandit
  - bandit -s B104 -r ${SRC_DIR}

pytest:
  stage: testing
  script:
  - python setup.py pytest
